exclude = []
source_roots = [
    ".",
]

[[modules]]
path = "core.auth.api"
depends_on = [
    { path = "core.auth.models" },
    { path = "core.auth.use_cases" },
    { path = "core.internal.api" },
    { path = "core.seedwork.api_layer" },
]

[[modules]]
path = "core.auth.domain"
depends_on = []

[[modules]]
path = "core.auth.forms"
depends_on = [
    { path = "core.auth.domain" },
    { path = "core.auth.models" },
    { path = "core.auth.use_cases" },
]

[[modules]]
path = "core.auth.models"
depends_on = [
    { path = "core.auth.domain" },
    { path = "core.auth.token_generator" },
    { path = "core.seedwork.aggregate" },
    { path = "core.seedwork.domain_layer" },
    { path = "core.seedwork.events_addon" },
]

[[modules]]
path = "core.auth.oidc_provider_settings"
depends_on = []

[[modules]]
path = "core.auth.token_generator"
depends_on = []

[[modules]]
path = "core.auth.use_cases"
depends_on = [
    { path = "core.auth.domain" },
    { path = "core.auth.models" },
    { path = "core.auth.token_generator" },
    { path = "core.seedwork.message_layer" },
    { path = "core.seedwork.use_case_layer" },
]

[[modules]]
path = "core.auth.usecases"
depends_on = [
    { path = "core.auth.use_cases" },
]

[[modules]]
path = "core.auth.views"
depends_on = [
    { path = "core.auth.forms" },
    { path = "core.auth.models" },
    { path = "core.auth.use_cases" },
]

[[modules]]
path = "core.collab.api"
depends_on = [
    { path = "core.auth.models" },
    { path = "core.collab.models" },
    { path = "core.collab.repositories" },
    { path = "core.seedwork.api_layer" },
]

[[modules]]
path = "core.collab.models"
depends_on = [
    { path = "core.auth.models" },
    { path = "core.collab.value_objects" },
    { path = "core.seedwork.aggregate" },
    { path = "core.seedwork.domain_layer" },
    { path = "core.seedwork.encryption" },
    { path = "core.seedwork.events_addon" },
]

[[modules]]
path = "core.collab.repositories"
depends_on = [
    { path = "core.auth.models" },
    { path = "core.collab.models" },
]

[[modules]]
path = "core.collab.use_cases"
depends_on = [
    { path = "core.auth.models" },
    { path = "core.collab.models" },
    { path = "core.collab.repositories" },
    { path = "core.seedwork.use_case_layer" },
]

[[modules]]
path = "core.collab.usecases"
depends_on = [
    { path = "core.collab.use_cases" },
    { path = "core.seedwork.use_case_layer" },
]

[[modules]]
path = "core.collab.value_objects"
depends_on = []

[[modules]]
path = "core.internal.api"
depends_on = [
    { path = "core.auth.api" },
    { path = "core.internal.models" },
    { path = "core.seedwork.api_layer" },
]

[[modules]]
path = "core.internal.models"
depends_on = []

[[modules]]
path = "core.seedwork.aggregate"
depends_on = []

[[modules]]
path = "core.seedwork.api_layer"
depends_on = [
    { path = "core.seedwork.domain_layer" },
    { path = "core.seedwork.use_case_layer" },
]

[[modules]]
path = "core.seedwork.cronjobs"
depends_on = [
    { path = "core.seedwork.api_layer" },
]

[[modules]]
path = "core.seedwork.domain_layer"
depends_on = []

[[modules]]
path = "core.seedwork.encryption"
depends_on = []

[[modules]]
path = "core.seedwork.events_addon"
depends_on = [
    { path = "core.seedwork.aggregate" },
]

[[modules]]
path = "core.seedwork.message_layer"
depends_on = []

[[modules]]
path = "core.seedwork.permission"
depends_on = []

[[modules]]
path = "core.seedwork.statistics"
depends_on = []

[[modules]]
path = "core.seedwork.storage"
depends_on = [
    { path = "core.seedwork.encryption" },
]

[[modules]]
path = "core.seedwork.storage_folders"
depends_on = []

[[modules]]
path = "core.seedwork.use_case_layer"
depends_on = [
    { path = "core.seedwork.domain_layer" },
]
